import { useState,useEffect } from 'react'
import { api } from '../api.js'
import ProductCard from '../components/ProductCard.jsx'
import LiveCounter from '../components/LiveCounter.jsx'

const hero='https://images.unsplash.com/photo-1606225457115-9b0c9b4f8b5f?auto=format&fit=crop&w=1800&q=85'
const hazelnut='https://images.unsplash.com/photo-1603052875302-d376b7c0638a?auto=format&fit=crop&w=1000&q=85'
const giresun='https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=85'

export default function Home(){
 const [products,setProducts]=useState([]),[showAll,setShowAll]=useState(false)
 useEffect(()=>{api('/products?page=1&category=&search=').then(d=>setProducts(d.items||[])).catch(()=>{})},[])
 return <div className="cagran-shell">
  <section className="bg-[#173b2a] text-white relative overflow-hidden"><div className="absolute inset-0 hero-grid hero-glow opacity-80"/><div className="max-w-7xl mx-auto px-5 py-16 md:py-24 relative grid lg:grid-cols-[1.05fr_.95fr] gap-10 items-center">
   <div className="fade-up"><span className="inline-flex rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs tracking-[.18em] uppercase">Giresun'dan • Üreticiden</span><h1 className="cagran-serif text-5xl md:text-7xl leading-[.98] mt-6 max-w-3xl">Karadeniz'in yeşili,<br/><span className="text-[#e1b85a]">Giresun'un fındığı.</span></h1><p className="text-white/70 text-base md:text-lg leading-7 max-w-xl mt-6">Kendi bahçemizden çıkan mahsulü, aradaki zinciri mümkün olduğunca kısaltarak doğrudan tüketiciyle buluşturuyoruz.</p><div className="flex flex-wrap gap-3 mt-8"><a href="#findik" className="rounded-full bg-[#e1b85a] text-[#173b2a] px-6 py-3 font-black">Fındığımızı keşfet</a><a href="#hikaye" className="rounded-full border border-white/20 px-6 py-3 font-bold">Hikâyemizi oku</a></div><div className="flex gap-7 mt-9 text-sm text-white/55"><span>🌿 Kendi bahçemiz</span><span>🤝 Doğrudan üretici</span><span>📦 Tüketiciye gönderim</span></div></div>
   <div className="relative"><div className="absolute -inset-5 bg-[#e1b85a]/10 blur-3xl rounded-full"/><div className="relative rounded-[2rem] overflow-hidden border border-white/15 soft-shadow"><img src={hero} className="w-full h-[430px] object-cover" alt="Giresun doğası ve fındık bahçeleri"/><div className="absolute bottom-4 left-4 right-4 bg-black/45 backdrop-blur-md rounded-2xl p-4"><div className="flex justify-between items-end"><div><div className="text-xs uppercase tracking-widest text-white/60">Bizim için fındık</div><div className="font-bold text-lg">Sadece ürün değil, emek.</div></div><span className="text-3xl">🌰</span></div></div></div></div>
  </div></section>

  <section id="findik" className="max-w-7xl mx-auto px-5 py-20"><div className="grid lg:grid-cols-2 gap-12 items-center"><div className="rounded-[2rem] overflow-hidden soft-shadow"><img src={hazelnut} className="w-full h-[480px] object-cover" alt="Giresun fındığı"/></div><div><span className="text-[#a36f28] text-xs uppercase tracking-[.2em] font-black">01 • Fındığımız</span><h2 className="cagran-serif text-4xl md:text-5xl text-[#173b2a] mt-3">Giresun yağlı fındığı neden farklı?</h2><p className="text-[#59655c] leading-7 mt-5">Giresun'un iklimi, eğimli arazileri ve Karadeniz'in nemli havası fındığın yetiştiği özel ortamı oluşturur. Bizim için kalite, ürün eve geldikten sonra değil; bahçedeki bakımından başlar.</p><div className="grid sm:grid-cols-2 gap-3 mt-7"><div className="bg-white border border-[#e1ddd2] rounded-2xl p-4"><b>🌱 Bahçeden</b><p className="text-sm text-[#6d756f] mt-1">Kendi üretimimizden çıkan mahsul.</p></div><div className="bg-white border border-[#e1ddd2] rounded-2xl p-4"><b>🥜 Giresun lezzeti</b><p className="text-sm text-[#6d756f] mt-1">Yağlı ve aroması belirgin fındık.</p></div><div className="bg-white border border-[#e1ddd2] rounded-2xl p-4"><b>🤲 El emeği</b><p className="text-sm text-[#6d756f] mt-1">Hasattan ayıklamaya kadar emek.</p></div><div className="bg-white border border-[#e1ddd2] rounded-2xl p-4"><b>📦 Doğrudan</b><p className="text-sm text-[#6d756f] mt-1">Üreticiden tüketiciye gönderim.</p></div></div></div></div></section>

  <section id="giresun" className="bg-[#e8e2d4]"><div className="max-w-7xl mx-auto px-5 py-20 grid lg:grid-cols-[.9fr_1.1fr] gap-12 items-center"><div><span className="text-[#a36f28] text-xs uppercase tracking-[.2em] font-black">02 • Giresun</span><h2 className="cagran-serif text-4xl md:text-5xl text-[#173b2a] mt-3">Fındığın yetiştiği yer, hikâyenin kendisi.</h2><p className="text-[#59655c] leading-7 mt-5">Giresun'u anlatmadan Giresun fındığını anlatmak eksik kalır. Dağ ile denizin arasına sıkışan bahçeler, yağmur, yamaçlar ve yıllardır süregelen üretim kültürü bu lezzetin parçasıdır.</p><div className="mt-7 flex gap-3 flex-wrap"><span className="px-4 py-2 rounded-full bg-white/70 text-sm">Karadeniz</span><span className="px-4 py-2 rounded-full bg-white/70 text-sm">Fındık bahçeleri</span><span className="px-4 py-2 rounded-full bg-white/70 text-sm">Üretim kültürü</span></div></div><div className="rounded-[2rem] overflow-hidden soft-shadow"><img src={giresun} className="w-full h-[390px] object-cover" alt="Karadeniz doğası"/></div></div></section>

  <section id="hikaye" className="max-w-4xl mx-auto px-5 py-20 text-center"><span className="text-[#a36f28] text-xs uppercase tracking-[.2em] font-black">03 • Üreticinin hikâyesi</span><h2 className="cagran-serif text-4xl md:text-5xl text-[#173b2a] mt-3">“Tüccara vermek yerine, emeğimi doğrudan anlatmak istedim.”</h2><p className="text-[#59655c] leading-8 mt-6 text-lg">Çağran'ın amacı büyük bir market olmak değil. Kendi mahsulünü tanıtmak, Giresun'u anlatmak ve isteyen tüketiciye üreticiden doğrudan ulaşabilme imkânı vermek.</p></section>

  <section id="uretim" className="bg-white border-y border-[#e4dfd3]"><div className="max-w-7xl mx-auto px-5 py-16"><div className="flex flex-wrap justify-between items-end gap-5"><div><span className="text-[#a36f28] text-xs uppercase tracking-[.2em] font-black">04 • Üretim</span><h2 className="cagran-serif text-4xl text-[#173b2a] mt-2">Bahçeden pakete</h2></div><p className="text-[#69736b] max-w-md text-sm leading-6">Her aşamayı görünür kılmak, tüketiciyle üretici arasındaki güveni büyütmek istiyoruz.</p></div><div className="grid md:grid-cols-4 gap-4 mt-9">{[['01','🌿','Bahçe','Ağaçların bakımı ve sezon hazırlığı'],['02','🥜','Hasat','Olgunlaşan ürünün toplanması'],['03','🧺','Ayıklama','Ürünün seçilmesi ve hazırlanması'],['04','📦','Gönderim','Siparişin tüketiciye ulaştırılması']].map(x=><div key={x[0]} className="rounded-2xl bg-[#f7f4ec] p-5"><span className="text-xs text-[#a36f28] font-black">{x[0]}</span><div className="text-3xl mt-5">{x[1]}</div><h3 className="font-black text-[#173b2a] mt-3">{x[2]}</h3><p className="text-sm text-[#68736a] mt-1 leading-5">{x[3]}</p></div>)}</div></div></section>

  <section className="max-w-7xl mx-auto px-5 py-20"><div className="rounded-[2rem] bg-[#173b2a] text-white p-7 md:p-10 flex flex-col md:flex-row gap-7 justify-between items-center"><div><div className="text-[#e1b85a] text-xs uppercase tracking-[.2em] font-black">05 • Üreticiden satın al</div><h2 className="cagran-serif text-3xl md:text-4xl mt-2">Mahsulden almak ister misiniz?</h2><p className="text-white/60 mt-2 max-w-xl">Ürün, fiyat, miktar ve kargo için doğrudan üreticiye ulaşabilirsiniz.</p></div><a href="https://wa.me/905XXXXXXXXX" target="_blank" rel="noreferrer" className="shrink-0 rounded-full bg-[#25D366] px-7 py-3.5 font-black">WhatsApp'tan sor</a></div></section>

  {products.length>0&&<section className="max-w-7xl mx-auto px-5 pb-20"><div className="flex items-end justify-between mb-6"><div><span className="text-[#a36f28] text-xs uppercase tracking-[.2em] font-black">Ürünler</span><h2 className="cagran-serif text-3xl text-[#173b2a] mt-2">Mevcut ürünler</h2></div><LiveCounter/></div><div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-5">{products.slice(0,showAll?products.length:8).map(p=><ProductCard key={p.id} p={p}/>)}</div>{products.length>8&&<div className="text-center mt-8"><button onClick={()=>setShowAll(!showAll)} className="rounded-full border border-[#173b2a] px-6 py-3 font-bold text-[#173b2a]">{showAll?'Daha az göster':'Tüm ürünleri göster'}</button></div>}</section>}
 </div>
}
